In [2]:
import numpy as np
from scipy.special import expit, logit
f= lambda c,x : 1 / (1 + np.e ** (-c * x))
y= lambda c,x : expit(-c*x)

In [3]:
x=np.array([1, 2, 3])
expit((-2*x))

array([0.11920292, 0.01798621, 0.00247262])

In [4]:
f(-2, 1)

0.11920292202211757

In [5]:
print(np.arange(-1.25, 1.25, 2.5 /10000))

[-1.25    -1.24975 -1.2495  ...  1.24925  1.2495   1.24975]


In [6]:
np.random.uniform(low=-2, high=2, size=int(np.sqrt(100000)))

array([ 1.00524223,  0.20653612, -1.1836702 ,  1.51598209,  0.54631528,
        1.53838179,  1.83427194,  0.97959529, -1.20412705, -1.75782172,
        0.29521094, -1.80951177, -1.9716513 ,  1.07053839, -0.56430539,
        0.77870075,  1.62013192, -1.47872848, -1.05929868,  1.40966804,
        0.44242511,  0.00699598, -0.62716636, -0.2300775 ,  0.53345631,
       -1.65431919, -0.21744943,  0.12315489, -1.7549766 , -0.70165323,
        0.39121879, -1.0830785 ,  0.31006819, -0.21465498, -0.50403991,
       -1.85091067, -0.11767723,  0.95126179,  0.80552303,  1.65550977,
       -1.43814969, -1.70260872, -0.80336635, -0.89047785,  0.84769471,
       -0.72770166, -0.16096658, -0.92139733,  1.72252293,  1.63788611,
       -1.44794465,  0.69681441,  0.21872329, -0.45747978,  1.40208961,
        0.75359686,  1.06582794,  0.28835233, -1.32223738, -1.26485706,
       -1.70398551,  0.46368268,  1.90751265, -1.93507628,  0.47309063,
        1.35258671,  1.75823879, -1.96689908, -1.67102744, -1.06

In [7]:
np.arange(-1.25, 1.25, 2.5 / np.sqrt(100000))

array([-1.25000000e+00, -1.24209431e+00, -1.23418861e+00, -1.22628292e+00,
       -1.21837722e+00, -1.21047153e+00, -1.20256584e+00, -1.19466014e+00,
       -1.18675445e+00, -1.17884875e+00, -1.17094306e+00, -1.16303736e+00,
       -1.15513167e+00, -1.14722598e+00, -1.13932028e+00, -1.13141459e+00,
       -1.12350889e+00, -1.11560320e+00, -1.10769751e+00, -1.09979181e+00,
       -1.09188612e+00, -1.08398042e+00, -1.07607473e+00, -1.06816903e+00,
       -1.06026334e+00, -1.05235765e+00, -1.04445195e+00, -1.03654626e+00,
       -1.02864056e+00, -1.02073487e+00, -1.01282918e+00, -1.00492348e+00,
       -9.97017787e-01, -9.89112093e-01, -9.81206399e-01, -9.73300705e-01,
       -9.65395011e-01, -9.57489316e-01, -9.49583622e-01, -9.41677928e-01,
       -9.33772234e-01, -9.25866540e-01, -9.17960846e-01, -9.10055152e-01,
       -9.02149457e-01, -8.94243763e-01, -8.86338069e-01, -8.78432375e-01,
       -8.70526681e-01, -8.62620987e-01, -8.54715292e-01, -8.46809598e-01,
       -8.38903904e-01, -

[-0.9976375  0.124353 ]


In [11]:
np.linalg.eig(weights)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [14]:
int(np.random.uniform(-2,2))

0